name: 'Composer run action'
author: 'May Meow'
description: 'Containerized environment to run composer script defined in composer.json file'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  composer_script:
    description: 'Enter name of composer command from your composer file'
    required: true
  memory_limit:
    description: 'Set php memory limit'
    required: false
    default: '1024M'
  code_path:
    description: 'Enter path to your code. Default is .'
    required: false
    default: '.'
  php_version:
    description: 'The PHP Version to use'
    required: false
    default: '8.2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.composer_script }}
    - ${{ inputs.memory_limit }}
    - ${{ inputs.code_path }}
    - ${{ inputs.php_version }}
